### ISSUE TITLE
VOID responses must be content negotiated for RDF responses

### ISSUE THREAD

**Issue by JervenBolleman** [dbcls/LinkedData-Agora#104]
The UniProt endpoint provides VOID descriptions of its data but do return HTML if no specific RDF format is  asked for.

[http://yummydata.org/endpoints/56/8378/log/void_ttl]

Suggest no such content request is done.

**Comment by yayamamo** [comment]
Thanks and we fixed to add the Accept header that indicates some RDF formats (text/turtle and application/rdf+xml)
