### ISSUE TITLE
The Query used to test Turtle format must be a CONSTRUCT or a DESCRIBE query

### ISSUE THREAD

**Issue by JervenBolleman** [dbcls/LinkedData-Agora#127]
```sparql
SELECT  *WHERE {        GRAPH ?g { ?s ?p ?o } .      }LIMIT 1
```
Should really be
```sparql
CONSTRUCT {?s ?p?o}
WHERE { GRAPH ?g { ?s ?p ?o } . }
LIMIT 1
```
When asking for content-type turtle. This is because SPARQL1.1 does not define an RDF output for the SELECT or ASK queries. Only construct and describe can give RDF output therefore a select is not valid..

**Comment by yayamamo** [comment]
When checking the code, we use the query you quoted to check whether an endpoint is alive or not, and therefore, as for this query, we do not think our crawler assumes any format.

**Comment by JervenBolleman** [comment]
Well, yes, but a very good endpoint like the uniprot.org one will tell the user that they are asking for the impossible and return a client error. Giving minus points :( 

It would be better to check that the query and content result matches to avoid penalizing endpoints that help the users.

**Comment by yayamamo** [comment]
Thank you for your comment. This issue has been fixed!
