### ISSUE TITLE
The test for fetching VOID files should set accept headers

### ISSUE THREAD

**Issue by JervenBolleman** [dbcls/LinkedData-Agora#129]
Some providers will give HTML rendering instead (possibly with JSON-LD or RDFa). This makes the response marked as invalid but would have been marked valid if the accept headers for rdf/xml and turtle had been set.

**Comment by yayamamo** [comment]
Thank you for your suggestion. I'll ask an engineer.

**Comment by yayamamo** [comment]
Could you please let me know some examples?

**Comment by JervenBolleman** [comment]
```
 wget --header "accept:application/rdf+xml" "http://sparql.uniprot.org/.well-known/void" -O - |less
```
compared to 

```
 wget --header "accept:*/*" "http://sparql.uniprot.org/.well-known/void" -O - |less
```

The second version is what is currently send by Umaka and the response we send in return is valid for that accept header.

**Comment by yayamamo** [comment]
Thank you, and we're working on this issue.

**Comment by yayamamo** [comment]
We're sorry for our late reply, and we adopted your suggestion. Thank you.
