### ISSUE TITLE
Content negotiation does not test endpoint but other services.

### ISSUE THREAD

**Issue by JervenBolleman** [dbcls/LinkedData-Agora#137]
e.g. http://yummydata.org/endpoints/56/46420/log/support_xml_format
tests the uniprot ftp and web site but not actually our sparql endpoint. 

I think this test should be written to just use content negotiation on the sparql endpoint using queries.

**Comment by yayamamo** [comment]
Thanks for your valuable comment. We found the cause and are working around it.
