### ISSUE TITLE
rdfs:seeAlso query for validatie uses http://identifiers.org/

### ISSUE THREAD

**Issue by egonw** [dbcls/LinkedData-Agora#160]
In this validation report:

![image](https://user-images.githubusercontent.com/26721/108498107-abf78980-72ac-11eb-8d98-47b74bb2c1e1.png)

The query has a `FILTER` at the end looking for `http://identifiers.org/`. I am not sure why that filter is there, but we actually switched in the February 2021 release to `https://identifiers.org/` URLs (httpS instead of http), so it no longer finds such `rdfs:seeAlso` and `owl:sameAs` links anymore.

**Comment by yayamamo** [comment]
It might be due to that the URIs beginning with "http://identifiers.org/" were assumed as primary ones in WikiPathways RDF data. Now it has been deleted.

**Comment by egonw** [comment]
Yes, we moved only this year from `http` to `https` (for identifiers.org). Thanks for the update!

**Comment by yayamamo** [comment]
Update done.
